# Generated by Django 6.0.6 on 2026-06-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField(unique=True, verbose_name='Артикул WB')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('my_current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена селлера')),
                ('min_acceptable_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Критический порог цены (демпинг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (Селлер)')),
            ],
            options={
                'verbose_name': 'Товар селлера',
                'verbose_name_plural': 'Товары селлеров',
            },
        ),
        migrations.CreateModel(
            name='DumpingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения')),
                ('lowest_competitor_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена конкурента')),
                ('deviation_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент отклонения')),
                ('lost_profit_rub', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Упущенная выгода (руб.)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.product', verbose_name='Наш товар')),
            ],
            options={
                'verbose_name': 'Сигнал о демпинге',
                'verbose_name_plural': 'Сигналы о демпинге',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_nm_id', models.BigIntegerField(verbose_name='Артикул конкурента')),
                ('competitor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя конкурента')),
                ('price_before_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена до скидки')),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Финальная цена')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='analytics.product', verbose_name='Наш товар')),
            ],
            options={
                'verbose_name': 'История цен конкурента',
                'verbose_name_plural': 'История цен конкурентов',
                'ordering': ['-checked_at'],
            },
        ),
    ]
