# Generated by Django 6.0.6 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Допустимая погрешность (%)'),
        ),
    ]
