# Generated by Django 6.0.6 on 2026-06-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_product_tolerance_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitorpricehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dumpingalert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='target_competitor_urls',
            field=models.TextField(blank=True, null=True, verbose_name='Артикулы конкурентов (через запятую)'),
        ),
        migrations.AlterField(
            model_name='competitorpricehistory',
            name='competitor_name',
            field=models.CharField(max_length=255, verbose_name='Имя конкурента'),
        ),
        migrations.AlterField(
            model_name='competitorpricehistory',
            name='competitor_nm_id',
            field=models.CharField(max_length=50, verbose_name='Артикул конкурента'),
        ),
        migrations.AlterField(
            model_name='competitorpricehistory',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до скидки'),
        ),
        migrations.AlterField(
            model_name='competitorpricehistory',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='competitorpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='analytics.product'),
        ),
        migrations.AlterField(
            model_name='dumpingalert',
            name='lost_profit_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Упущенная выгода (руб)'),
        ),
        migrations.AlterField(
            model_name='dumpingalert',
            name='lowest_competitor_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Мин. цена конкурента'),
        ),
        migrations.AlterField(
            model_name='dumpingalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_acceptable_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимально допустимая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Моя текущая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nm_id',
            field=models.CharField(max_length=50, verbose_name='Артикул WB'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент терпимости (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Селлер'),
        ),
    ]
